// Auto-generated by admin server
window.COLLECTIONS = [
  { "slug": "automotive", "title": "Automotive", "blurb": "Cars, bikes, and machines", "cover": "images/automobile/gr86/wide-GR86.jpg" },
  { "slug": "lifestyle", "title": "Lifestyle", "blurb": "Places, people, and moments", "cover": "images/lifestyle/detroit/DOH.jpg" }
];

window.PROJECTS = [
  { "slug": "gr86", "collection": "automotive", "title": "Toyota GR86", "year": "2024", "location": "Warren, MI", "blurb": "Track-ready sports car", "cover": "images/automobile/gr86/wide-GR86.jpg" },
  { "slug": "s2000", "collection": "automotive", "title": "Honda S2000", "year": "2024", "location": "Sterling Heights, MI", "blurb": "High-revving roadster", "cover": "images/automobile/s2000/badge.jpg" },
  { "slug": "yamaha-r3", "collection": "automotive", "title": "Yamaha R3", "year": "2024", "location": "Sterling Heights, MI", "blurb": "Sport motorcycle", "cover": "images/automobile/Yamaha_R3/bike.jpg" },
  { "slug": "gt3rs", "collection": "automotive", "title": "Porsche GT3 RS", "year": "2024", "location": "Troy, MI", "blurb": "Track-focused Porsche", "cover": "images/automobile/gt3rs/gt3rs.jpeg" },
  { "slug": "ford-gt", "collection": "automotive", "title": "Ford GT", "year": "2024", "location": "Troy, MI", "blurb": "American supercar", "cover": "images/automobile/ford_gt/wheel-lg.jpg" },
  { "slug": "japan", "collection": "lifestyle", "title": "Japan", "year": "2026", "location": "Tokyo, Japan", "blurb": "Streets of Tokyo", "cover": "images/lifestyle/japan/1777474571487-IMG_2196.jpg" },
  { "slug": "detroit", "collection": "lifestyle", "title": "Detroit", "year": "2024", "location": "Detroit, MI", "blurb": "Motor City", "cover": "images/lifestyle/detroit/DOH.jpg" }
];

window.PHOTOS = {
  "gr86": [
    { "srcSmall": "images/automobile/gr86/wide-GR86.jpg", "srcLarge": "images/automobile/gr86/wide-GR86.jpg", "w": 0, "h": 0, "title": "Wide GR86", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automobile/gr86/front-GR86.jpg", "srcLarge": "images/automobile/gr86/front-GR86.jpg", "w": 0, "h": 0, "title": "Front GR86", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automobile/gr86/rear-GR86.jpg", "srcLarge": "images/automobile/gr86/rear-GR86.jpg", "w": 0, "h": 0, "title": "Rear GR86", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automobile/gr86/wheel-GR86.jpg", "srcLarge": "images/automobile/gr86/wheel-GR86.jpg", "w": 0, "h": 0, "title": "Wheel GR86", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automobile/gr86/gr86-lg.jpg", "srcLarge": "images/automobile/gr86/gr86-lg.jpg", "w": 0, "h": 0, "title": "GR86", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automobile/gr86/detroit1.jpg", "srcLarge": "images/automobile/gr86/detroit1.jpg", "w": 0, "h": 0, "title": "Detroit Auto Show 1", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Detroit, MI", "lat": "42.3314", "lng": "-83.0458" } },
    { "srcSmall": "images/automobile/gr86/detroit2.jpg", "srcLarge": "images/automobile/gr86/detroit2.jpg", "w": 0, "h": 0, "title": "Detroit Auto Show 2", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Detroit, MI", "lat": "42.3314", "lng": "-83.0458" } },
    { "srcSmall": "images/automobile/gr86/detroit3.jpg", "srcLarge": "images/automobile/gr86/detroit3.jpg", "w": 0, "h": 0, "title": "Detroit Auto Show 3", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Detroit, MI", "lat": "42.3314", "lng": "-83.0458" } },
    { "srcSmall": "images/automotive/gr86/1760627923527-MAA.jpg", "srcLarge": "images/automotive/gr86/1760627923527-MAA.jpg", "w": 0, "h": 0, "title": "GR86 Session 1", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automotive/gr86/1760628076412-MAA.jpg", "srcLarge": "images/automotive/gr86/1760628076412-MAA.jpg", "w": 0, "h": 0, "title": "GR86 Session 2", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automotive/gr86/1760628078843-MAA.jpg", "srcLarge": "images/automotive/gr86/1760628078843-MAA.jpg", "w": 0, "h": 0, "title": "GR86 Session 3", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } },
    { "srcSmall": "images/automotive/gr86/1760628172148-MAA.jpg", "srcLarge": "images/automotive/gr86/1760628172148-MAA.jpg", "w": 0, "h": 0, "title": "GR86 Session 4", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Warren, MI", "lat": "42.4928", "lng": "-83.0277" } }
  ],
  "s2000": [
    { "srcSmall": "images/automobile/s2000/badge.jpg", "srcLarge": "images/automobile/s2000/badge.jpg", "w": 0, "h": 0, "title": "S2000 Badge", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } },
    { "srcSmall": "images/automobile/s2000/IMG_0086-2.jpg", "srcLarge": "images/automobile/s2000/IMG_0086-2.jpg", "w": 0, "h": 0, "title": "S2000", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } },
    { "srcSmall": "images/automobile/s2000/IMG_0090-2.jpg", "srcLarge": "images/automobile/s2000/IMG_0090-2.jpg", "w": 0, "h": 0, "title": "S2000 Detail", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } },
    { "srcSmall": "images/automobile/s2000/wheel.jpg", "srcLarge": "images/automobile/s2000/wheel.jpg", "w": 0, "h": 0, "title": "S2000 Wheel", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } }
  ],
  "yamaha-r3": [
    { "srcSmall": "images/automobile/Yamaha_R3/bike.jpg", "srcLarge": "images/automobile/Yamaha_R3/bike.jpg", "w": 0, "h": 0, "title": "Yamaha R3", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } },
    { "srcSmall": "images/automobile/Yamaha_R3/broken.jpg", "srcLarge": "images/automobile/Yamaha_R3/broken.jpg", "w": 0, "h": 0, "title": "R3 Broken", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } },
    { "srcSmall": "images/automobile/Yamaha_R3/moose.jpg", "srcLarge": "images/automobile/Yamaha_R3/moose.jpg", "w": 0, "h": 0, "title": "R3 Moose", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Sterling Heights, MI", "lat": "42.5803", "lng": "-83.0302" } }
  ],
  "gt3rs": [
    { "srcSmall": "images/automobile/gt3rs/gt3rs.jpeg", "srcLarge": "images/automobile/gt3rs/gt3rs.jpeg", "w": 0, "h": 0, "title": "GT3 RS", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Troy, MI", "lat": "42.6064", "lng": "-83.1498" } },
    { "srcSmall": "images/automobile/gt3rs/topdown-lg.jpg", "srcLarge": "images/automobile/gt3rs/topdown-lg.jpg", "w": 0, "h": 0, "title": "GT3 RS Top Down", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Troy, MI", "lat": "42.6064", "lng": "-83.1498" } },
    { "srcSmall": "images/automobile/gt3rs/03-lg.jpg", "srcLarge": "images/automobile/gt3rs/03-lg.jpg", "w": 0, "h": 0, "title": "GT3 RS 03", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Troy, MI", "lat": "42.6064", "lng": "-83.1498" } }
  ],
  "ford-gt": [
    { "srcSmall": "images/automobile/ford_gt/wheel-lg.jpg", "srcLarge": "images/automobile/ford_gt/wheel-lg.jpg", "w": 0, "h": 0, "title": "Ford GT Wheel", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Troy, MI", "lat": "42.6064", "lng": "-83.1498" } }
  ],
  "japan": [
    { "srcSmall": "images/lifestyle/japan/1777474571487-IMG_2196.jpg", "srcLarge": "images/lifestyle/japan/1777474571487-IMG_2196.jpg", "w": 0, "h": 0, "title": "Japan", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Tokyo, Japan", "lat": "35.6762", "lng": "139.6503" } },
    { "srcSmall": "images/lifestyle/japan/1777474571498-IMG_2488.jpg", "srcLarge": "images/lifestyle/japan/1777474571498-IMG_2488.jpg", "w": 0, "h": 0, "title": "Japan 2", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Tokyo, Japan", "lat": "35.6762", "lng": "139.6503" } }
  ],
  "detroit": [
    { "srcSmall": "images/lifestyle/detroit/DOH.jpg", "srcLarge": "images/lifestyle/detroit/DOH.jpg", "w": 0, "h": 0, "title": "Detroit", "story": "", "meta": { "camera": "", "lens": "", "shutter": "", "aperture": "", "iso": "", "focalLength": "", "location": "Detroit, MI", "lat": "42.3314", "lng": "-83.0458" } }
  ]
};
