const path = require('path');
const express = require('express');
const multer = require('multer');
const fs = require('fs-extra');
const { execFile } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || '127.0.0.1';

const ROOT = path.resolve(__dirname);
const IMAGES_DIR = path.join(ROOT, 'images');
const DATA_JS = path.join(ROOT, 'data.js');
const DATA_JSON = path.join(ROOT, 'data.json');

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serve the existing static site at root
app.use(express.static(ROOT));

// Admin UI
app.get('/admin', (req, res) => res.sendFile(path.join(ROOT, 'admin.html')));

// Helper: load existing data from data.js if present, otherwise fallback to data.json or empty
function loadData() {
  let data = { COLLECTIONS: [], PROJECTS: [], PHOTOS: {} };
  try {
    if (fs.existsSync(DATA_JSON)) {
      const j = fs.readFileSync(DATA_JSON, 'utf8');
      const parsed = JSON.parse(j);
      data = Object.assign(data, parsed);
    } else if (fs.existsSync(DATA_JS)) {
      // naive eval: read data.js and extract window.* assignments
      const src = fs.readFileSync(DATA_JS, 'utf8');
      // try to find window.COLLECTIONS = ...; etc
      const extract = (name) => {
        const re = new RegExp(name + '\\s*=\\s*(\[.*?\]|\{[\s\S]*?\});', 'm');
        const m = src.match(re);
        if (m) return eval('(' + m[1] + ')');
        return null;
      };
      const cols = extract('window.COLLECTIONS');
      const projs = extract('window.PROJECTS');
      const photos = extract('window.PHOTOS');
      if (cols) data.COLLECTIONS = cols;
      if (projs) data.PROJECTS = projs;
      if (photos) data.PHOTOS = photos;
    }
  } catch (e) {
    console.error('Error loading data:', e);
  }
  return data;
}

function saveData(data) {
  fs.writeFileSync(DATA_JSON, JSON.stringify(data, null, 2), 'utf8');
  // regenerate data.js for compatibility with current site (window.* assignments)
  const js = `// Auto-generated by admin server\nwindow.COLLECTIONS = ${JSON.stringify(data.COLLECTIONS, null, 2)};\n\nwindow.PROJECTS = ${JSON.stringify(data.PROJECTS, null, 2)};\n\nwindow.PHOTOS = ${JSON.stringify(data.PHOTOS, null, 2)};\n`;
  fs.writeFileSync(DATA_JS, js, 'utf8');
}

// Initialize data on server start — only write data.json if it doesn't exist yet.
// Never overwrite data.js on startup so manual edits are preserved.
let DATA = loadData();
if (!fs.existsSync(DATA_JSON)) {
  fs.writeFileSync(DATA_JSON, JSON.stringify(DATA, null, 2), 'utf8');
}

// Setup multer storage to a temp folder; we'll move files into place after metadata is known
const upload = multer({ dest: path.join(ROOT, 'tmp_uploads') });

// API: upload image file with fields: collection, project (optional), filename (optional)
app.post('/api/upload-image', upload.single('file'), async (req, res) => {
  try {
    const file = req.file;
    const collection = req.body.collection || 'uncategorized';
    const project = req.body.project || '';
    if (!file) return res.status(400).json({ error: 'No file uploaded' });

    const colDir = path.join(IMAGES_DIR, collection);
    await fs.ensureDir(colDir);
    const destDir = project ? path.join(colDir, project) : colDir;
    await fs.ensureDir(destDir);

    // Auto-convert HEIC/HEIF → JPEG so browsers can display them
    const isHeic = /\.(heic|heif)$/i.test(file.originalname);
    const baseName = isHeic
      ? file.originalname.replace(/\.(heic|heif)$/i, '.jpg')
      : file.originalname;
    const name = `${Date.now()}-${baseName}`;
    const destPath = path.join(destDir, name);

    if (isHeic) {
      // Use macOS sips for HEIC → JPEG conversion
      await new Promise((resolve, reject) => {
        execFile('sips', ['-s', 'format', 'jpeg', file.path, '--out', destPath], (err) => {
          if (err) reject(err); else resolve();
        });
      });
      await fs.remove(file.path);
    } else {
      await fs.move(file.path, destPath, { overwrite: false });
    }

    // Return path relative to site root
    const rel = path.relative(ROOT, destPath).split(path.sep).join('/');
    res.json({ ok: true, path: rel });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: e.message });
  }
});

// API: add collection
app.post('/api/add-collection', (req, res) => {
  const { slug, title, blurb, cover } = req.body;
  if (!slug || !title) return res.status(400).json({ error: 'slug and title required' });
  if (DATA.COLLECTIONS.find(c => c.slug === slug)) return res.status(409).json({ error: 'collection exists' });
  const col = { slug, title, blurb: blurb || '', cover: cover || '' };
  DATA.COLLECTIONS.push(col);
  saveData(DATA);
  res.json({ ok: true, collection: col });
});

// API: add project
app.post('/api/add-project', (req, res) => {
  const { slug, collection, title, year, location, blurb, cover } = req.body;
  if (!slug || !collection || !title) return res.status(400).json({ error: 'slug, collection and title required' });
  if (DATA.PROJECTS.find(p => p.slug === slug)) return res.status(409).json({ error: 'project exists' });
  const proj = { slug, collection, title, year: year || '', location: location || '', blurb: blurb || '', cover: cover || '' };
  DATA.PROJECTS.push(proj);
  saveData(DATA);
  res.json({ ok: true, project: proj });
});

// API: add photo metadata to a project
app.post('/api/add-photo', (req, res) => {
  const { project, srcSmall, srcLarge, w, h, title, story, meta } = req.body;
  if (!project || !srcSmall) return res.status(400).json({ error: 'project and srcSmall required' });
  try {
    if (!DATA.PHOTOS[project]) DATA.PHOTOS[project] = [];
    const entry = {
      srcSmall,
      srcLarge: srcLarge || srcSmall,
      w: w || 0,
      h: h || 0,
      title: title || '',
      story: story || '',
      meta: meta || {}
    };
    DATA.PHOTOS[project].push(entry);
    saveData(DATA);
    res.json({ ok: true, entry });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: e.message });
  }
});

// API: list data
app.get('/api/data', (req, res) => res.json(DATA));

// API: delete collection
app.delete('/api/collection/:slug', (req, res) => {
  const { slug } = req.params;
  const idx = DATA.COLLECTIONS.findIndex(c => c.slug === slug);
  if (idx === -1) return res.status(404).json({ error: 'not found' });
  DATA.COLLECTIONS.splice(idx, 1);
  saveData(DATA);
  res.json({ ok: true });
});

// API: delete project
app.delete('/api/project/:slug', (req, res) => {
  const { slug } = req.params;
  const idx = DATA.PROJECTS.findIndex(p => p.slug === slug);
  if (idx === -1) return res.status(404).json({ error: 'not found' });
  DATA.PROJECTS.splice(idx, 1);
  delete DATA.PHOTOS[slug];
  saveData(DATA);
  res.json({ ok: true });
});

// API: delete photo by project + index
app.delete('/api/photo/:project/:index', (req, res) => {
  const { project, index } = req.params;
  const i = parseInt(index, 10);
  if (!DATA.PHOTOS[project] || !DATA.PHOTOS[project][i]) return res.status(404).json({ error: 'not found' });
  DATA.PHOTOS[project].splice(i, 1);
  saveData(DATA);
  res.json({ ok: true });
});

// API: set cover for a project
app.post('/api/set-cover', (req, res) => {
  const { project, cover } = req.body;
  if (!project || !cover) return res.status(400).json({ error: 'project and cover required' });
  const proj = DATA.PROJECTS.find(p => p.slug === project);
  if (!proj) return res.status(404).json({ error: 'project not found' });
  proj.cover = cover;
  saveData(DATA);
  res.json({ ok: true, cover });
});

app.listen(PORT, HOST, () => {
  console.log(`Admin server running at http://${HOST}:${PORT}/ — admin UI: http://${HOST}:${PORT}/admin`);
});
